import fs from 'node:fs';
import path from 'node:path';

type DistFile = {
	relPath: string;
	absPath: string;
};

function fail(message: string, stderr?: string): never {
	if (stderr && stderr.length > 0) {
		throw new Error(`${message}\n${stderr}`);
	}

	throw new Error(message);
}

function walk(dir: string, relPrefix: string, files: DistFile[]): void {
	for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
		const rel = path.join(relPrefix, entry.name);
		const abs = path.join(dir, entry.name);
		if (entry.isDirectory()) {
			walk(abs, rel, files);
			continue;
		}

		if (entry.isFile()) {
			files.push({ relPath: rel, absPath: abs });
		}
	}
}

export async function prepareAssets(): Promise<void> {
	const webBuild = Bun.spawnSync(['pnpm', 'run', 'build'], { cwd: '../web' });
	if (webBuild.exitCode !== 0) {
		fail('Web build failed:', webBuild.stderr.toString());
	}

	const distDir = '../web/dist';
	const files: DistFile[] = [];
	walk(distDir, '', files);

	if (
		!files.some((file) => file.relPath.replace(/\\/g, '/') === 'index.html')
	) {
		throw new Error('Expected index.html in web dist');
	}

	const genDir = '.gen';
	fs.mkdirSync(genDir, { recursive: true });

	const imports = files.map((file, index) => {
		const importPath = path.posix.join('../../web/dist', file.relPath);
		return `import file_${index} from '${importPath}' with { type: 'file' };`;
	});

	const mapEntries = files.map((file, index) => {
		const urlPath = `/${file.relPath.replace(/\\/g, '/')}`;
		return `  '${urlPath}': file_${index}`;
	});

	const genContent = `// @ts-nocheck
// Auto-generated by scripts/prepare-assets.ts — do not edit manually
${imports.join('\n')}

const filemap: Record<string, string> = {
${mapEntries.join(',\n')}
};

export default filemap;
`;

	fs.writeFileSync(path.join(genDir, 'web-ui.gen.ts'), genContent, 'utf-8');

	const genMigrations = Bun.spawnSync([
		'pnpm',
		'--dir',
		'../../services/engine',
		'run',
		'gen-migrations',
	]);
	if (genMigrations.exitCode !== 0) {
		fail(
			'Migration bundle generation failed:',
			genMigrations.stderr.toString(),
		);
	}
}
